extends RefCounted
class_name ArenaLayout

const TILE_RENDER_SIZE := Vector2i(64, 64)

const MAIN_ROOM_COLUMNS := 22
const MAIN_ROOM_ROWS := 16

const CORRIDOR_COLUMNS := 6
const CORRIDOR_ROWS := 4
const CORRIDOR_START_COLUMN := int((MAIN_ROOM_COLUMNS - CORRIDOR_COLUMNS) / 2)

const ROOM_WIDTH := MAIN_ROOM_COLUMNS * TILE_RENDER_SIZE.x
const ROOM_HEIGHT := MAIN_ROOM_ROWS * TILE_RENDER_SIZE.y

const CORRIDOR_WIDTH := CORRIDOR_COLUMNS * TILE_RENDER_SIZE.x
const CORRIDOR_HEIGHT := CORRIDOR_ROWS * TILE_RENDER_SIZE.y
const CORRIDOR_LEFT := CORRIDOR_START_COLUMN * TILE_RENDER_SIZE.x
const CORRIDOR_RIGHT := CORRIDOR_LEFT + CORRIDOR_WIDTH
const CORRIDOR_TOP := -CORRIDOR_HEIGHT

const WORLD_LEFT := 0
const WORLD_TOP := CORRIDOR_TOP
const WORLD_RIGHT := ROOM_WIDTH
const WORLD_BOTTOM := ROOM_HEIGHT
